import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/navigation/NavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Watch-tube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-main h-screen">
        <NavBar />
      </main>
    </>
  );
};

export default Home;
